In [1]:
import numpy as np

In [2]:
a=np.array([8,6,5])

In [3]:
print(a.shape)

(3,)


In [4]:
k=np.array([(3,8,4),(9,3,5),(11,15,17),(19,15,4)])
print(k.shape)
print(k)

(4, 3)
[[ 3  8  4]
 [ 9  3  5]
 [11 15 17]
 [19 15  4]]


In [5]:
m=np.array([([3,41],[8,41],[4,61]),([9,5],[3,8],[5,6]),([11,3],[15,12],[15,17]),([19,5],[15,5],[4,5])])

In [6]:
m

array([[[ 3, 41],
        [ 8, 41],
        [ 4, 61]],

       [[ 9,  5],
        [ 3,  8],
        [ 5,  6]],

       [[11,  3],
        [15, 12],
        [15, 17]],

       [[19,  5],
        [15,  5],
        [ 4,  5]]])

In [7]:
m.shape

(4, 3, 2)

In [8]:
print(k[0:5:1,2])

[ 4  5 17  4]


In [9]:
print(k[0:5:1,2].shape)

(4,)


In [10]:
print(k[:,-1:])


[[ 4]
 [ 5]
 [17]
 [ 4]]


In [11]:
print(k[1:,2])

[ 5 17  4]


In [12]:
print(m[1:,1:,1:])


[[[ 8]
  [ 6]]

 [[12]
  [17]]

 [[ 5]
  [ 5]]]


In [13]:
print(k[1:3,1:4])

[[ 3  5]
 [15 17]]


In [14]:
print(m[1:3,1:4])

[[[ 3  8]
  [ 5  6]]

 [[15 12]
  [15 17]]]


In [15]:
print(k+5)

[[ 8 13  9]
 [14  8 10]
 [16 20 22]
 [24 20  9]]


In [16]:
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 15,  4]])

In [17]:
k[:2]

array([[3, 8, 4],
       [9, 3, 5]])

In [18]:
k[2:]

array([[11, 15, 17],
       [19, 15,  4]])

In [19]:
(k[:,1])=[1,2,3,4]

In [20]:
k

array([[ 3,  1,  4],
       [ 9,  2,  5],
       [11,  3, 17],
       [19,  4,  4]])

In [21]:
k[:2,1:]=[[1,2],[3,4]]
k

array([[ 3,  1,  2],
       [ 9,  3,  4],
       [11,  3, 17],
       [19,  4,  4]])

In [22]:
np.append(k,[[1,1,1]],axis=0)


array([[ 3,  1,  2],
       [ 9,  3,  4],
       [11,  3, 17],
       [19,  4,  4],
       [ 1,  1,  1]])

In [23]:
np.append(k,[[1],[1],[1],[1]],axis=1)

array([[ 3,  1,  2,  1],
       [ 9,  3,  4,  1],
       [11,  3, 17,  1],
       [19,  4,  4,  1]])

In [24]:
np.delete(k,1,0)

array([[ 3,  1,  2],
       [11,  3, 17],
       [19,  4,  4]])

In [25]:
np.delete(k,1,axis=0)

array([[ 3,  1,  2],
       [11,  3, 17],
       [19,  4,  4]])

In [26]:
k.reshape(6,2)

array([[ 3,  1],
       [ 2,  9],
       [ 3,  4],
       [11,  3],
       [17, 19],
       [ 4,  4]])

In [27]:
k.reshape(2,2,3)

array([[[ 3,  1,  2],
        [ 9,  3,  4]],

       [[11,  3, 17],
        [19,  4,  4]]])

In [28]:
k.dtype

dtype('int32')

In [29]:
k.astype('uint16')

array([[ 3,  1,  2],
       [ 9,  3,  4],
       [11,  3, 17],
       [19,  4,  4]], dtype=uint16)

In [30]:
k.astype(float)

array([[ 3.,  1.,  2.],
       [ 9.,  3.,  4.],
       [11.,  3., 17.],
       [19.,  4.,  4.]])

In [31]:
k.sum(axis=0)

array([42, 11, 27])

In [32]:
k.mean(axis=0)

array([10.5 ,  2.75,  6.75])

In [33]:
k.std(axis=1)

array([0.81649658, 2.62466929, 5.73488351, 7.07106781])

In [34]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [36]:
np.random.randint(1,15,[3,4])

array([[10,  4, 12, 10],
       [14,  7,  4,  7],
       [10,  4,  5, 10]])