In [36]:
import numpy as np


In [37]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [39]:
np.arange(1,11,4)

array([1, 5, 9])

In [40]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [42]:
np.random.randint(1,6,[4,3,2])

array([[[4, 2],
        [5, 2],
        [5, 2]],

       [[2, 5],
        [4, 3],
        [1, 4]],

       [[5, 3],
        [1, 2],
        [3, 1]],

       [[1, 4],
        [2, 4],
        [5, 2]]])

In [43]:
np.random.seed(10)
np.random.randint(1,6,[4,3])

array([[2, 5, 1],
       [2, 4, 5],
       [2, 1, 2],
       [3, 1, 2]])

In [44]:
np.random.rand(3,4)

array([[0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [45]:
np.loadtxt('day2.txt' ,dtype=str)

array(['hey', 'there,', 'Vanshika', 'here'], dtype='<U8')

In [52]:
np.loadtxt('day2-2.txt')

array([[ 4.,  8., 11., 12.],
       [12., 11.,  8.,  4.]])

In [54]:
p=np.random.rand(3,4)
print(p)

[[0.90864888 0.31923609 0.09045935 0.30070006]
 [0.11398436 0.82868133 0.04689632 0.62628715]
 [0.54758616 0.819287   0.19894754 0.8568503 ]]


In [56]:
np.savetxt('new.txt', p, delimiter=' ')

In [57]:
-m pip install opencv-python

SyntaxError: invalid syntax (3133217262.py, line 1)